Init script improvements
- Safety check that we are really in a nixkell repo before nuking .git
- Deletes itself after run

diff --git a/init b/init
--- a/init
+++ b/init
@@ -7,16 +7,23 @@ set -euo pipefail
 # Start in project root
 cd "$(dirname "${BASH_SOURCE[0]}")/"
 
-project_name=${PWD##*/}
+# Make sure the git repo is in fact nixkell before we nuke it
+repo_url=$(git config --get remote.origin.url)
+if [[ $(basename -s .git "$repo_url") != "nixkell" ]]; then
+  echo "Not a nixkell repository, aborting..."
+  exit 1
+fi
 
-# Nuke nixkell's own .git and license
+# Nuke nixkell's .git and license
 rm -rf .git
 rm LICENSE
 
-# Fresh readme
+project_name=${PWD##*/}
+
+# Blank slate readme
 echo "# $project_name" > README.md
 
-# Replace dummy "replaceme" project name with the real one
+# Replace the dummy "replaceme" project names throughout with the actual one
 nix_files=$(find . -type f -name "*.nix")
 for i in $nix_files; do
   sed -i "s/replaceme/$project_name/g" "$i"
@@ -26,3 +33,6 @@ sed -i "s/replaceme/$project_name/g" ./bin/Main.hs
 
 # Fire up the nix shell
 direnv allow .
+
+# Finally delete this script
+rm -f init
